services:
  np-projekt-app:
    image: np-projekt-app
    restart: on-failure
    build:
      context: ./np-projekt-app
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./np-projekt-app:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
