# Dokumentacje oraz inne źródła, których używaliśmy podczas tworzenia tego pliku
# https://docs.gitea.com/installation/install-with-docker
# https://www.jenkins.io/doc/book/installing/docker/
# https://umasrinivask.medium.com/configure-nginx-as-a-reverse-proxy-with-docker-compose-file-4ebba2b75c89
networks:
  gitea:
    external: false

services:
  svn:
    image: gitea/gitea:1.21.11
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://myserv.local/svn
      # Bez tego Gitea nie jest w stanie powiadomić Jenkinsa o zmianach w repozytorium
      - GITEA__webhook__ALLOWED_HOST_LIST=myserv.local
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22" 
  jenkins:
    image: jenkins
    build:
      # Używamy "customowego" obrazu Jenkinsa z zainstalowanym Dockerem
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/ci"
    volumes:
      - ./jenkins-data/jenkins_home:/var/jenkins_home
      # Aby uchronić się przed uruchamianiem Dockera w Dockerze, przekazujemy za pomocą
      # wolumenu socket dockera z hosta do instancji Jenkinsa.
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    container_name: nginx_rp
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svn
      - jenkins